### ISSUE TITLE
Autosize item height to grid item content

### ISSUE THREAD

**Issue by zm-sky** [bensladden/vue-responsive-dash#121]
I didnt see anything for this in the documentation, unless I missed it
Is there a way to have a grid item autosize itself to the content's height?
My use case is fetching data from my API and populating widgets with it, so they're bound to be different heights

**Comment by bensladden** [comment]
Hi,
All grid items share the same height as defined by rowHeight prop on the layout. Typically i go the reverse way round and make the widgets resize to the gridItem: [https://vue-responsive-dash-vuetify.netlify.app/#/](https://vue-responsive-dash-vuetify.netlify.app/#/)

**Comment by zm-sky** [comment]
Unfortunately, i cannot do this the opposite way, as heights can differ significantly from one element to another. Doing it the way you proposed will not work for my use case

Perhaps a solution to this is being able to calculate an item's total height in grid units, and assigning the new height value to the layout

**Comment by bensladden** [comment]
Sounds like you have a plan, Note check the src code for DashItem.model.ts for the converison you are after: 
` 
static getWidthFromPx(widthPx: number, colWidth: number, margin: Margin) {
    return Math.round((widthPx + margin.x) / (colWidth + margin.x));
  }

  static getHeightInPx(h: number, rowHeight: number, margin: Margin) {
    return Math.round(rowHeight * h + Math.max(0, h - 1) * margin.y);
  }
`

Note im not sure its totally what you are after as it will round to the nearest INT

**Comment by bensladden** [comment]
Ill Close this for now, any questions you know where to find me

**Comment by Victor7095** [comment]
I'm having a problem creating a draggable dashboard.
The charts grows over the wrapping div.
In the example you provided, each card contains 1 chart inside that has the same width & height as the container. But if you add a padding to the card, the chart grows beyond the card and can overlap other cards.
The same will happen if add a card header to the card, because the chart assumes the height of the full card.
See this:
![image](https://user-images.githubusercontent.com/36238607/112042561-0854ff80-8b1e-11eb-98d1-5116683e509a.png)
