### ISSUE TITLE
Request: Be able to move by grabbing any of the child elements

### ISSUE THREAD

**Issue by TheBraveBunny** [bensladden/vue-responsive-dash#67]
Currently, this library works when having empty panels that you are moving around. It seems that if you have content inside the panels, to move, you need to actually grab the panel background.

Example:
![image](https://user-images.githubusercontent.com/8333959/75004093-e53db500-541e-11ea-983d-3f839e94da87.png)

When I put an overlay over the panel, I have to grab the pixel of white border to be able to move the item. The button also doesn't let me move the panel either.

**Comment by bensladden** [comment]
What z-index is the overlay. It is most likely the cause of the issues. The z-Index of the drag overlay is only 1.

I could potentially make the zIndex a prop for the panel. Otherwise i would have to guess what level to set it at. (Some programmers may want an overlay to prevent interaction below. ) Thoughts?

**Comment by TheBraveBunny** [comment]
That definitely solved the issue for me! For others, I think it might be useful to have an optional prop for specifying the zIndex. Then, they could have specific elements (like a move icon) that the user could grab to move around the panel rather than anywhere on the entire panel.
