### ISSUE TITLE
Request: Don't move items until after the dragged item is dropped

### ISSUE THREAD

**Issue by TheBraveBunny** [bensladden/vue-responsive-dash#68]
It seems that displaying the red placeholder panel permanently moves the other panels, even if the item doesn't get dropped there. With the new compact prop, it would be nice if the items array doesn't get permanently changed until the item drop.

Example:

1) before move
![image](https://user-images.githubusercontent.com/8333959/75066241-50c76700-549f-11ea-93e0-4020e00c8b38.png)

2) moving rightmost top panel to leftmost top position
![image](https://user-images.githubusercontent.com/8333959/75066288-6d639f00-549f-11ea-8168-9a059b1c4c4c.png)

I would want the general and description panels to move down, but I would want the background panel not to move.

**Comment by bensladden** [comment]
This request will require a bit of thought as the lib is not really setup for this. The purpose of the red placeholder is to show where the item will end up.  It also acts as a base to move the other panels out of the way. You are correct in seeing that when compact=false the panels do not move back up once its moved passed. The problem i face is the code does not know the difference between an intentional spare space and a spare space due to a item moving around. The only thing i can think of is to make use of the the @moveStart, @moving, @moveEnd, @resizeStart, @resizing and @resizeEnd events. To keep track of the moving item and record the layout when starting. Then doing some sort of comparism at the end where you put the original layout items back where they were if the dragged item is not going to cause a collision.

**Comment by bensladden** [comment]
Did you have any luck with this?
